### ISSUE TITLE
Installation doesn't seem to work (presumably because of google code shutdown)

### ISSUE THREAD

**Issue by rrthomas** [bhenderson/netrc#1]
```
$ go get github.com/bhenderson/netrc
package code.google.com/p/go-netrc/netrc: unable to detect version control system for code.google.com/ path
```

There seem to be multiple GitHub sources of this now, of varying degrees of canonicality and up-to-dateness, including fhs/go-netrc and bgentry/go-netrc.

**Comment by bhenderson** [comment]
interesting, thanks.

at first blush, fhs/go-netrc looks like the same as code.google.com, just with imports changed.
I'll keep poking. do you have a suggestion?

**Comment by rrthomas** [comment]
Thanks for fixing this!
